version: '2.3'

services:
   sign-spotter:
     container_name: sign-spotter
     build: ./
     restart: always
     ports:
      - '8888:8888'
      - '6006:6006'
     volumes:
      - ~/sign-spotter-model:/models/research/object_detection/sign-spotter
     environment:
      - DISPLAY=$DISPLAY
